### ISSUE TITLE
other commands : how ?

### ISSUE THREAD

**Issue by tissatussa** [alcides-schulz/Tucano#14]
after giving the command 'help' i see this text :

```
Other commands that can be used:

             d: display current board
          eval: print evaluation score for current position
epd <filename>: locate best move for epd positions in the file
     perft <n>: show perft move count from current position.
                other perft commands: perftx, perfty, perftz
          tune: evaluation tuning menu
          ppst: print current pst values
```

indeed, 'd' shows the diagram of the current position, but the commands 'tune', 'eval' and 'ppst' do not work : nothing happens -- i use v10.08.

btw. the 'perftx' command seems nice : it shows # captures, ep, castlings and more .. but what about the other perft commands ? Any description ?

**Comment by alcides-schulz** [comment]
Hi, thanks for looking at this and reporting. This help menu needed some update. I just made some changes and updated the codebase.
- eval is outdated, it was used to show some additional information because the eval was hand crafted, e.g. pawn structure eval, king safety, pst's , etc. Now with neural network we don't have this information so I removed this option.
- epd still used, so I added some additional note regarding the format.
- perft's commands, also added some additional information for those commands. perfty counts the moves for a position and display the counts for each depth. So I added the labels. Perftz count the moves for special cases where the move generation can be trick.
- tune is also deprecated, use to tune hand crafted evals, using texel tuning method.
- ppst is also deprecated with nn evals.

ok, hope this clarifies, and let me know any other question. This will be live in the next release. I'm training a new network so hopefully in the next month or so.

Thanks again for pointing this out.

Alcides.

**Comment by tissatussa** [comment]
> ..This help menu needed some update..

that's what i thought .. yes, please update the code a bit, so the 'help' items are helpful again, otherwise they may only lead to confusion, haha..

Btw. i decided to use your `perftx` code to create a binary which does only that .. so, i removed all other (engine) code and compiled a new binary, just for experimenting with the special amounts 'captures', 'checks' etc. .. i'm not a C programmer but i find your code very well structured, so i could use my own logic to hack this private little project.

[ i'm on Xubuntu 22.04 ]

**Comment by alcides-schulz** [comment]
thanks, and good luck with your project! perftx was very useful to find issues with move generation function.
