### ISSUE TITLE
Same network

### ISSUE THREAD

**Issue by SzotsGabor** [alcides-schulz/Tucano#15]
Hi Alcides,

The network file in 11 is the same as in 10. How is it simplified then? Or is it not needed? Then why is it in the package?

Gabor Szots
CCRL testing group

**Comment by alcides-schulz** [comment]
Hi Gabor,
The file was included by mistake, I just created a new release 11.00.1 that fixes that. You can delete the file from your folder.
It is not necessary anymore since the network is simplified, the weights are in the file eval_nn.h, so it is incorporated during compilation.
Thanks for pointing that out and sorry for the inconvenience.
Alcides.
