### ISSUE TITLE
doesnt compile on ubuntu

### ISSUE THREAD

**Issue by LocutusOfPenguin** [alcides-schulz/Tucano#4]
Hi,
trying it on linux i get:

src/eval_tune.c:62:5: error: unknown type name ‘HANDLE’
     HANDLE  thread_id;

plus several warnings with format using printf

Jürgen

**Comment by alcides-schulz** [comment]
Hi, eval_tune.c is used to tune evaluation parameters. It is a development utility I use. You can exclude it from the compilation since it is not used during runtime. You can try to recompile and let me know how it goes.
Should be fixed on the next version, since I am updating this file to use the same structure as the rest of the program, I will make sure to compile it gcc.
thanks.

**Comment by LocutusOfPenguin** [comment]
Ok, moved the file out and i had to change yr linux line to:
gcc -o tucano -O3 -flto -m64 -mtune=generic -s -Wfatal-errors  src/*.c -lpthread -lm
=> libs at end

compiled. But "uci" command is not understood (i know "go movetime" works, but "uci" etc is needed first). Im also not sure, yr PV output is like uci should be -> no time see:
For the next 3weeks im off btw.

**Comment by alcides-schulz** [comment]
Tucano is a xboard engine, not UCI. Those are the two engine protocols, and tucano uses xboard. For example, instead of "uci" you can type in "xboard", that will show the xboard initial response. Also if you type in "help" it will show some information. Usually you can install tucano as xboard engine in a GUI program. I'm not sure which one exists for linux. I think cutechess may be a good one. You can find it here in github. Anyway let me know if you need any information i can try to help. Thanks for testing tucano, and sorry I didn't see your initial request earlier, kind of busy at work.

**Comment by LocutusOfPenguin** [comment]
Oh   I didn't realized this before   I'm main developer of Picochess  and we use uci only   so sadly we don't come together

**Comment by alcides-schulz** [comment]
oh I see. I may add support some day for UCI. I will let you know then. Currently is working for xboard, but it is good to have uci too, it is very popular.
Thanks again, and let me know anything.
