### ISSUE TITLE
Tucano half the speed running on 4 threads on linux and NNUE mode

### ISSUE THREAD

**Issue by emdio** [alcides-schulz/Tucano#9]
I compiled Tucano with the sse4 version. Running it on 1 thread gave almost twice the performance than with the "-threads 4" option running the speed command on NNUE mode.
The top command indicates that the Tucano process is in fact using more than 100% of the cpu.

$ ./tucano_sse4 -threads 4
Tucano chess engine by Alcides Schulz - 10.00 (type 'help' for information)

Eval file './tucano_nn01.bin' loaded !
   hash table: 64 MB, threads: 4

speed
running speed test 1 of 5...
running speed test 2 of 5...
running speed test 3 of 5...
running speed test 4 of 5...
running speed test 5 of 5...

Speed test: nodes per second average =  313k

*******************************************************************

$ ./tucano_sse4
Tucano chess engine by Alcides Schulz - 10.00 (type 'help' for information)

Eval file './tucano_nn01.bin' loaded !
   hash table: 64 MB, threads: 1

speed
running speed test 1 of 5...
running speed test 2 of 5...
running speed test 3 of 5...
running speed test 4 of 5...
running speed test 5 of 5...

Speed test: nodes per second average =  612k

**Comment by alcides-schulz** [comment]
Hi, thanks for reporting. I'm going to take a look at the speed command. I think it may not be prepared to run on more than one thread. I created this command for single threads actually. But let me take a look and confirm. Let you know. thanks.

**Comment by alcides-schulz** [comment]
Hi emdio,
Just pushed an update, there was an error, it was not counting nodes from other threads. 
Thanks.

**Comment by emdio** [comment]
The speed command seems to work now, but I find issues with the "bench" command. Tucano in 1 th
read is faster than in 4 threads, BUT the nodes per second is bigger in 4 threads (?)
![tucano_bench](https://user-images.githubusercontent.com/1314942/150758636-8ad08291-8079-4efa-9240-fb7fcf0ed890.jpg)

**Comment by alcides-schulz** [comment]
Hi, glad it worked, but regarding the bench command is designed to run on one thread only. The bench idea is to provide the signature number, which can be used to validate that compile is good, since I provide the number when making a release. It is quick way to check the compilation. We can reproduce this signature number with one thread, but not when running with multiple threads, it becomes not deterministic, we don't know how many nodes each thread can search. With one thread we are able to repeat the same number.
Not sure this explains, let me any questions. Thanks.

**Comment by emdio** [comment]
Thanks for not closing the issue and allowing new questions.

What really bothers me is the fact that the bench command takes more time in 4 threads than in 1 thread (10.78s in 1 thread versus 13.95s in 4 threads in the picture I posted above). I mean, the point of parallelizing is making the engine faster rather than counting more nodes per second.

And this 1 thread being faster than 4 also happens in the speed command (speed command doesn't show the time it takes, but it's an estimation I've made "manually").

**Comment by alcides-schulz** [comment]
I think I understand you question, it has to do with how the multi thread is implemented in chess engines. Tucano and other engines implement what is called "lazy SMP". Basically all the threads will search the same position, each one with a slight difference in depth, and the information is shared via transposition table between the threads. You can see some more information in https://www.chessprogramming.org/Lazy_SMP. Seems not logical, but it is simple to implement and maintain. Implementing other types of SMP architectures didn't' show to be significantly better, that's why most engines use lazy smp.
So, when you run with 4 threads, the work will not be split between them, but all 4 will search the same starting positions. So that's why the time is not reduced but the number of nodes will increase. 
Ok, let me know if this answer the question.
